# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ExtractSubsector
                                 A QGIS plugin
 Etapa 1 do HeloDel
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2019-11-04
        git sha              : $Format:%H$
        copyright            : (C) 2019 by SUPGEP/CASAL
        email                : supgep.e1@casal.al.gov.br
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from PyQt5.QtWidgets import QAction, QFileDialog, QMenu
from qgis.core import QgsProject, Qgis, QgsVectorLayer
from qgis.utils import iface
import processing

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .extract_subsector_dialog import ExtractSubsectorDialog
import os.path


class ExtractSubsector:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'ExtractSubsector_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Extract Subsector')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('ExtractSubsector', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToVectorMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        """icon_path = ':/plugins/extract_subsector/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Extract Subsector'),
            callback=self.run,
            parent=self.iface.mainWindow())"""

        # will be set False in run()
        self.first_start = True
        
        self.actionRun = QAction(QIcon("/home/gedop/.local/share/QGIS/QGIS3/profiles/default/python/plugins/helonoi/icon.png"),"Extract Subsector", self.iface.mainWindow())
        self.iface.addPluginToVectorMenu("&HeloDel", self.actionRun)
        self.actionRun.triggered.connect(self.run)


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginVectorMenu(
                self.tr(u'&Extract Subsector'),
                action)
            self.iface.removeToolBarIcon(action)
    
    def populate_cb_camadas(self):
        #clear combobox 1 before populate it
        self.dlg.cb_camadas.clear()
        #populate the combobox
        layers = QgsProject.instance().mapLayers().values()
        self.dlg.cb_camadas.addItems([layer.name() for layer in layers])
    
    def on_cb_camadas_change(self):
        layers = QgsProject.instance().mapLayers().values()
        #clear combobox 2 before populate it
        self.dlg.cb_campos.clear()
        # retrieve the values to populate combobox2
        # get the current value of combobox 1
        values = []
        selectedLayerText = self.dlg.cb_camadas.currentText()
        for layer in layers:
            if layer.name() == selectedLayerText:
                values = layer.fields().names()
        self.dlg.cb_campos.addItems(values)

    def select_output_directory(self):
        filename = QFileDialog.getExistingDirectory(None, "Selecione o diretório de saída")
        self.dlg.lineEdit.setText(filename)

    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = ExtractSubsectorDialog()
            self.dlg.pushButton.clicked.connect(self.select_output_directory)

        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            layers = QgsProject.instance().mapLayers().values()
            selectedLayerText = self.dlg.cb_camadas.currentText()
            for layer in layers:
                if layer.name() == selectedLayerText:
                    selectedLayer = layer.source()
            selectedField = self.dlg.cb_campos.currentText()
            path = self.dlg.lineEdit.text()
            output = processing.run("qgis:splitvectorlayer", {'INPUT': selectedLayer,'FIELD': selectedField, 'OUTPUT': path})
            output_layers = output['OUTPUT_LAYERS']
            for layer in output_layers:
                iface.addVectorLayer(layer, "", "ogr")
            self.iface.messageBar().pushMessage("Success", "Output file written at " + path,level=Qgis.Success, duration=3)
