# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PointsByVoronoi
                                 A QGIS plugin
 Etapa 7 do HeloDel
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2019-11-04
        git sha              : $Format:%H$
        copyright            : (C) 2019 by SUPGEP/CASAL
        email                : supgep.e1@casal.al.gov.br
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction
from PyQt5.QtWidgets import QAction, QFileDialog, QMenu, QToolButton
from qgis.core import QgsProject, Qgis, QgsVectorLayer
from qgis.utils import iface

import dbf
import processing


# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .points_by_voronoi_dialog import PointsByVoronoiDialog
import os.path


class PointsByVoronoi:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'PointsByVoronoi_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Points by Voronoi')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('PointsByVoronoi', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToVectorMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        """icon_path = ':/plugins/points_by_voronoi/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Points by Voronoi'),
            callback=self.run,
            parent=self.iface.mainWindow())"""

        # will be set False in run()
        self.first_start = True
        
        self.actionRun = QAction(QIcon("/home/gedop/.local/share/QGIS/QGIS3/profiles/default/python/plugins/helonoi/icon.png"),"Points by Voronoi", self.iface.mainWindow())
        self.iface.addPluginToVectorMenu("&HeloDel", self.actionRun)
        self.actionRun.triggered.connect(self.run)

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginVectorMenu(
                self.tr(u'&Points by Voronoi'),
                action)
            self.iface.removeToolBarIcon(action)
    
    def select_voronoi_files1(self):
        filenames, _filter = QFileDialog.getOpenFileNames(self.dlg, "Selecione os arquivos dos polígonos de Voronoi")
        self.dlg.lineEdit_1.setText(', '.join(filenames))
    
    def select_voronoi_files2(self):
        filenames, _filter = QFileDialog.getOpenFileNames(self.dlg, "Selecione os arquivos dos polígonos de Voronoi")
        self.dlg.lineEdit_5.setText(', '.join(filenames))
    
    def select_voronoi_files3(self):
        filenames, _filter = QFileDialog.getOpenFileNames(self.dlg, "Selecione os arquivos dos polígonos de Voronoi")
        self.dlg.lineEdit_8.setText(', '.join(filenames))
        
    def select_lig_files(self):
        filename, _filter = QFileDialog.getOpenFileName(self.dlg, "Selecione o arquivo de ligações")
        self.dlg.lineEdit_2.setText(filename)
    
    def select_vazamento_files(self):
        filename, _filter = QFileDialog.getOpenFileName(self.dlg, "Selecione o arquivo de vazamentos")
        self.dlg.lineEdit_6.setText(filename)
    
    def select_manometria_files(self):
        filename, _filter = QFileDialog.getOpenFileName(self.dlg, "Selecione o arquivo de vazamentos")
        self.dlg.lineEdit_9.setText(filename)
    
    def select_output_directory1(self):
        filename = QFileDialog.getExistingDirectory(None, "Selecione o diretório de saída")
        self.dlg.lineEdit_3.setText(filename)
    
    def select_output_directory2(self):
        filename = QFileDialog.getExistingDirectory(None, "Selecione o diretório de saída")
        self.dlg.lineEdit_7.setText(filename)
    
    def select_output_directory3(self):
        filename = QFileDialog.getExistingDirectory(None, "Selecione o diretório de saída")
        self.dlg.lineEdit_10.setText(filename)

    def select_junc_file(self):
        filename, _filter = QFileDialog.getOpenFileName(self.dlg, "Selecione o arquivo de nós")
        self.dlg.lineEdit_4.setText(filename)
        
    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = PointsByVoronoiDialog()
            self.dlg.pushButton_1.clicked.connect(self.select_voronoi_files1)
            self.dlg.pushButton_5.clicked.connect(self.select_voronoi_files2)
            self.dlg.pushButton_8.clicked.connect(self.select_voronoi_files3)
            self.dlg.pushButton_2.clicked.connect(self.select_lig_files)
            self.dlg.pushButton_6.clicked.connect(self.select_vazamento_files)
            self.dlg.pushButton_9.clicked.connect(self.select_manometria_files)
            self.dlg.pushButton_3.clicked.connect(self.select_output_directory1)
            self.dlg.pushButton_7.clicked.connect(self.select_output_directory2)
            self.dlg.pushButton_10.clicked.connect(self.select_output_directory3)
            self.dlg.pushButton_4.clicked.connect(self.select_junc_file)

        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            if self.dlg.lineEdit_1.text() != "":
                arquivos_voronois = self.dlg.lineEdit_1.text().split(', ')
                camada_ligacoes = self.dlg.lineEdit_2.text()
                junctions = self.dlg.lineEdit_4.text()[0:-4]+'.dbf'
                for voronoi in arquivos_voronois:
                    arq_saida = self.dlg.lineEdit_3.text() + '/' + camada_ligacoes.split('/')[-1][0:-4] + '_' + voronoi.split('/')[-1][0:-5] + ".shp"
                    processing.run("qgis:clip", {'INPUT': camada_ligacoes,'OVERLAY': voronoi, 'OUTPUT': arq_saida})
                    
                    node_id = arq_saida.split('_')[-1][0:-4]
                    
                    #Abrindo a tabela
                    tabela = dbf.Table('%s'%(arq_saida[0:-4]+'.dbf'))
                    tabela.open(mode=dbf.READ_WRITE)
                    #ler cada dado
                    soma = 0
                    for item in tabela:
                        try:
                            soma += float(item['Consumo'])
                        except:
                            continue
                    tabela.close()
                    
                    consumo_base = 0
                    consumo_base = soma*0.0003858
                    tabela_junctions = dbf.Table(junctions)
                    tabela_junctions.open(mode=dbf.READ_WRITE)
                    for item in tabela_junctions:
                        if item['node_id'].replace(" ", "") == node_id:
                            dbf.write(item, demand = consumo_base)
                    tabela_junctions.close()
    
                    #print(str(soma) + ' m³/s')
                    #print(str(consumo_base) + ' L/s')
    
                    iface.addVectorLayer(arq_saida, "", "ogr")
                    self.iface.messageBar().pushMessage("Success", "Output file written at " + arq_saida,level=Qgis.Success, duration=3)
                iface.addVectorLayer(junctions, "", "ogr")
            if self.dlg.lineEdit_5.text() != "":
                arquivos_voronois = self.dlg.lineEdit_5.text().split(', ')
                camada_vazamentos = self.dlg.lineEdit_6.text()            
                for voronoi in arquivos_voronois:
                    arq_saida = self.dlg.lineEdit_7.text() + '/' + camada_vazamentos.split('/')[-1][0:-4] + '_' + voronoi.split('/')[-1][0:-5] + ".shp"
                    processing.run("qgis:clip", {'INPUT': camada_vazamentos,'OVERLAY': voronoi, 'OUTPUT': arq_saida})
                    iface.addVectorLayer(arq_saida, "", "ogr")
                    self.iface.messageBar().pushMessage("Success", "Output file written at " + arq_saida,level=Qgis.Success, duration=3)
            if self.dlg.lineEdit_8.text() != "":
                arquivos_voronois = self.dlg.lineEdit_8.text().split(', ')
                camada_manometria = self.dlg.lineEdit_9.text()            
                for voronoi in arquivos_voronois:
                    arq_saida = self.dlg.lineEdit_10.text() + '/' + camada_manometria.split('/')[-1][0:-4] + '_' + voronoi.split('/')[-1][0:-5] + ".shp"
                    processing.run("qgis:clip", {'INPUT': camada_manometria,'OVERLAY': voronoi, 'OUTPUT': arq_saida})
                    iface.addVectorLayer(arq_saida, "", "ogr")
                    self.iface.messageBar().pushMessage("Success", "Output file written at " + arq_saida,level=Qgis.Success, duration=3)
            else:
                pass
